//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PACKINGSEAL.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmUniqloState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmUniqloState"]));
            }
            set
            {
                this["frmUniqloState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmUniqloLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["frmUniqloLocation"]));
            }
            set
            {
                this["frmUniqloLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size frmUniqloSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["frmUniqloSize"]));
            }
            set
            {
                this["frmUniqloSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmMontbellState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmMontbellState"]));
            }
            set
            {
                this["frmMontbellState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMontbellLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["frmMontbellLocation"]));
            }
            set
            {
                this["frmMontbellLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size frmMontbellSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["frmMontbellSize"]));
            }
            set
            {
                this["frmMontbellSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmMujiState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmMujiState"]));
            }
            set
            {
                this["frmMujiState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMujiLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["frmMujiLocation"]));
            }
            set
            {
                this["frmMujiLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size frmMujiSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["frmMujiSize"]));
            }
            set
            {
                this["frmMujiSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmSakuraiState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmSakuraiState"]));
            }
            set
            {
                this["frmSakuraiState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmSakuraiLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["frmSakuraiLocation"]));
            }
            set
            {
                this["frmSakuraiLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size frmSakuraiSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["frmSakuraiSize"]));
            }
            set
            {
                this["frmSakuraiSize"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmThermalUAState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmThermalUAState"]));
            }
            set
            {
                this["frmThermalUAState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmThermalUALocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["frmThermalUALocation"]));
            }
            set
            {
                this["frmThermalUALocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size frmThermalUASize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["frmThermalUASize"]));
            }
            set
            {
                this["frmThermalUASize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmKonicaUAState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmKonicaUAState"]));
            }
            set
            {
                this["frmKonicaUAState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmKonicaUALocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["frmKonicaUALocation"]));
            }
            set
            {
                this["frmKonicaUALocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size frmKonicaUASize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["frmKonicaUASize"]));
            }
            set
            {
                this["frmKonicaUASize"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmAsicsState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmAsicsState"]));
            }
            set
            {
                this["frmAsicsState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmAsicsLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["frmAsicsLocation"]));
            }
            set
            {
                this["frmAsicsLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size frmAsicsSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["frmAsicsSize"]));
            }
            set
            {
                this["frmAsicsSize"] = value;
            }
        }
    }

}
